# Site settings
title: Scott Preston's GitHub Page
email: github@scottpreston.com
description: > # this means to ignore newlines until "baseurl:"
  This is just some stuff I'm working on. I'm usually sharing it because it's cool
  or I'm giving a presentation on something realted to it. Check it out. Have fun. Contact
  me if you have any questions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottpreston.github.io" # the base hostname & protocol for your site
twitter_username: scottpreston
github_username:  scottpreston

# Build settings
markdown: kramdown
